---
- name: Backup, Replace WebLogic Files, Uninstall & Install Java on Windows Server - PROD Environment
  hosts: prod_weblogic_win
  gather_facts: no
  
  vars:
    # Configurable paths - can be overridden per environment
    oracle_home: "E:\\Oracle\\Middleware\\Oracle_Home"
    backup_dir: "E:\\Oracle\\backup"
    java_source_dir: "E:\\Java_source"
    java_installer: "jdk-8u441-windows-x64.exe"
    java_install_dir: "E:\\jdk1.8.0_441"
    
    # WebLogic domain configuration
    weblogic_domain: "base_domain"
    
    # Source files on Ansible server
    ansible_source_dir: "/home/appadmin/Upgrade_weblogic_files"
    
    # File Replacement Variables - Define what to search for and replace
    # These can be easily modified to match your specific file content
    file_replacements:
      # .globalEnv.properties file
      - file: "{{ oracle_home }}\\oui\\.globalEnv.properties"
        search_pattern: "{{ search_java_home | default('JAVA_HOME=') }}"
        replace_with: "JAVA_HOME={{ java_install_dir }}\\bin\\java.exe"
        description: "Java Home in Global Environment"
        
      - file: "{{ oracle_home }}\\oui\\.globalEnv.properties"
        search_pattern: "{{ search_weblogic_home | default('WL_HOME=') }}"
        replace_with: "WL_HOME={{ oracle_home }}\\wlserver"
        description: "WebLogic Home in Global Environment"
        
      # nodemanager.properties file
      - file: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\nodemanager\\nodemanager.properties"
        search_pattern: "{{ search_nodemanager_java | default('JavaHome=') }}"
        replace_with: "JavaHome={{ java_install_dir }}"
        description: "Java Home in Node Manager"
        
      # setNMJavaHome.cmd file
      - file: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setNMJavaHome.cmd"
        search_pattern: "{{ search_setnm_java | default('set JAVA_HOME=') }}"
        replace_with: "set JAVA_HOME={{ java_install_dir }}"
        description: "Java Home in Set NM Java Home Script"
        
      # setDomainEnv.cmd file
      - file: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setDomainEnv.cmd"
        search_pattern: "{{ search_domain_java | default('set JAVA_HOME=') }}"
        replace_with: "set JAVA_HOME={{ java_install_dir }}"
        description: "Java Home in Domain Environment"
        
      - file: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setDomainEnv.cmd"
        search_pattern: "{{ search_domain_path | default('set PATH=') }}"
        replace_with: "set PATH=%JAVA_HOME%\\bin;%PATH%"
        description: "PATH in Domain Environment"
    
    # Customizable search patterns (can be overridden via command line)
    search_java_home: "{{ search_java_home | default('JAVA_HOME=') }}"
    search_weblogic_home: "{{ search_weblogic_home | default('WL_HOME=') }}"
    search_nodemanager_java: "{{ search_nodemanager_java | default('JavaHome=') }}"
    search_setnm_java: "{{ search_setnm_java | default('set JAVA_HOME=') }}"
    search_domain_java: "{{ search_domain_java | default('set JAVA_HOME=') }}"
    search_domain_path: "{{ search_domain_path | default('set PATH=') }}"
    
  pre_tasks:
    - name: Start WebLogic Upgrade Process
      debug:
        msg: |
          === WebLogic Upgrade Started ===
          Target Host: {{ inventory_hostname }}
          Environment: PROD
          Timestamp: {{ ansible_date_time.iso8601 }}
          
  tasks:
    ### Ensure Backup Directory Exists
    - name: Create Backup Directory
      win_file:
        path: "{{ backup_dir }}"
        state: directory

    ### Define WebLogic Files for Backup
    - name: Set File Backup List
      set_fact:
        files_to_backup:
          - path: "{{ oracle_home }}\\oui\\.globalEnv.properties"
            description: "Oracle Global Environment Properties"
          - path: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\nodemanager\\nodemanager.properties"
            description: "Node Manager Properties"
          - path: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setNMJavaHome.cmd"
            description: "Node Manager Java Home Script"
          - path: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setDomainEnv.cmd"
            description: "Domain Environment Script"

    ### Backup WebLogic Configuration Files
    - name: Backup WebLogic Files with Timestamp
      win_shell: |
        $filePath = "{{ item.path }}"
        $backupDir = "{{ backup_dir }}"
        $timestamp = Get-Date -Format 'yyyyMMddHHmmss'
        $fileName = [System.IO.Path]::GetFileName($filePath)
        $backupFile = "$backupDir\$fileName`_$timestamp"
        
        If (Test-Path $filePath) {
            Copy-Item -Path $filePath -Destination $backupFile
            Write-Output "Backup created at $backupFile"
        } else {
            Write-Output "No existing file to backup: $filePath"
        }
      args:
        executable: powershell
      loop: "{{ files_to_backup }}"
      register: backup_results

    - name: Display Backup Status
      debug:
        msg: "{{ backup_results.results | map(attribute='stdout_lines') | list }}"

    ### Check if WebLogic files exist
    - name: Check if WebLogic files exist
      win_stat:
        path: "{{ item.dest }}"
      loop:
        - { src: ".globalEnv.properties", dest: "{{ oracle_home }}\\oui\\.globalEnv.properties" }
        - { src: "nodemanager.properties", dest: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\nodemanager\\nodemanager.properties" }
        - { src: "setNMJavaHome.cmd", dest: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setNMJavaHome.cmd" }
        - { src: "setDomainEnv.cmd", dest: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setDomainEnv.cmd" }
      register: file_check_results

    - name: Display file existence status
      debug:
        msg: "File {{ item.item.dest }} exists: {{ item.stat.exists }}"
      loop: "{{ file_check_results.results }}"

    - name: Display WebLogic Configuration Updates to be Applied
      debug:
        msg: |
          === WebLogic Configuration Updates ===
          File: {{ item.file }}
          Search Pattern: {{ item.search_pattern }}
          Replace With: {{ item.replace_with }}
          Description: {{ item.description }}
      loop: "{{ file_replacements }}"

    - name: Update WebLogic Configuration Files (Direct Modification)
      win_lineinfile:
        path: "{{ item.file }}"
        regexp: "{{ item.search_pattern }}.*"
        line: "{{ item.replace_with }}"
        backrefs: yes
      loop: "{{ file_replacements }}"
      when: 
        - item.file is defined
        - item.search_pattern is defined
        - item.replace_with is defined
      register: file_update_results

    ### Uninstall Existing Java (Safe, Tolerant)
    - name: Uninstall existing Java versions
      win_shell: |
        $apps = Get-WmiObject -Class Win32_Product | Where-Object {
          $_.Name -like "Java*" -or $_.Name -like "*JDK*"
        }

        foreach ($app in $apps) {
          Write-Output "Uninstalling: $($app.Name)"
          try {
            $null = $app.Uninstall()
          } catch {
            Write-Output "Failed to uninstall $($app.Name): $($_.Exception.Message)"
          }
        }

        if (-not $apps) {
          Write-Output "No existing Java installations found."
        }
      args:
        executable: powershell
      register: uninstall_java_result
      ignore_errors: true

    - name: Display Java Uninstall Results
      debug:
        msg: "{{ uninstall_java_result.stdout_lines }}"

    ### Kill All Java Processes Before Installation
    - name: Kill all running Java processes
      win_shell: |
        $javaProcs = Get-Process java -ErrorAction SilentlyContinue
        if ($javaProcs) {
          Stop-Process -Name java -Force
          Write-Output "Java processes killed."
        } else {
          Write-Output "No Java processes running."
        }
      args:
        executable: powershell
      register: kill_java_result

    - name: Display Java Kill Result
      debug:
        msg: "{{ kill_java_result.stdout_lines }}"

    ### Copy Java Installer to Windows Server
    - name: Copy Java Installer to Windows Server
      win_copy:
        src: "{{ ansible_source_dir }}/{{ java_installer }}"
        dest: "{{ java_source_dir }}\\{{ java_installer }}"

    ### Install Java JDK
    - name: Install Java JDK
      win_shell: "{{ java_source_dir }}\\{{ java_installer }} /s INSTALLDIR={{ java_install_dir }}"
      args:
        chdir: "{{ java_source_dir }}"

    ### Set JAVA_HOME Environment Variable
    - name: Set JAVA_HOME Environment Variable
      win_environment:
        name: JAVA_HOME
        value: "{{ java_install_dir }}"
        level: machine

    ### Add Java to System PATH
    - name: Add Java to System PATH
      win_path:
        elements:
          - "{{ java_install_dir }}\\bin"

    ### Get WebLogic Version Using Installed Java
    - name: Get WebLogic Version
      win_shell: |
        $env:JAVA_HOME = "{{ java_install_dir }}"
        $env:PATH = "$env:JAVA_HOME\bin;$env:PATH"
        & "$env:JAVA_HOME\bin\java.exe" -cp "{{ oracle_home }}\wlserver\server\lib\weblogic.jar" weblogic.version
      register: weblogic_version_output

    - name: Display WebLogic Version
      debug:
        msg: "{{ weblogic_version_output.stdout_lines }}"

    ### Verify Java Installation
    - name: Verify Java Installation
      win_shell: |
        $env:JAVA_HOME = "{{ java_install_dir }}"
        $env:PATH = "$env:JAVA_HOME\bin;$env:PATH"
        & "$env:JAVA_HOME\bin\java.exe" -version
      register: java_version_output

    - name: Display Java Version
      debug:
        msg: "{{ java_version_output.stdout_lines }}"

  post_tasks:
    - name: Log WebLogic Upgrade Completion
      debug:
        msg: |
          === WebLogic Upgrade Completed ===
          Target Host: {{ inventory_hostname }}
          Environment: PROD
          Completion Time: {{ ansible_date_time.iso8601 }}
          Status: SUCCESS
          
    - name: Generate Execution Summary Report
      set_fact:
        execution_summary:
          host: "{{ inventory_hostname }}"
          environment: "PROD"
          backup_files: "{{ backup_results.results | length }}"
          files_updated: "{{ file_update_results.results | default([]) | length }}"
          java_uninstalled: "{{ uninstall_java_result.stdout_lines | length }}"
          java_installed: "{{ java_install_dir }}"
          weblogic_version: "{{ weblogic_version_output.stdout_lines | first | default('N/A') }}"
          java_version: "{{ java_version_output.stdout_lines | first | default('N/A') }}"
          execution_time: "{{ ansible_date_time.iso8601 }}"
          
    - name: Display Final Execution Summary
      debug:
        msg: |
          === FINAL EXECUTION SUMMARY ===
          Host: {{ execution_summary.host }}
          Environment: {{ execution_summary.environment }}
          Backup Files: {{ execution_summary.backup_files }}
          Files Updated: {{ execution_summary.files_updated }}
          Java Uninstalled: {{ execution_summary.java_uninstalled }}
          Java Installation Path: {{ execution_summary.java_installed }}
          WebLogic Version: {{ execution_summary.weblogic_version }}
          Java Version: {{ execution_summary.java_version }}
          Execution Time: {{ execution_summary.execution_time }}
