---
- name: Backup, Replace WebLogic Files, Uninstall & Install Java on Windows Server - PROD Environment
  hosts: prod_weblogic_win
  gather_facts: no
  
  # Jenkins Pipeline Compatibility
  serial: 1  # Execute one host at a time for better control
  max_fail_percentage: 0  # Fail fast if any host fails
  
  vars:
    # Configurable paths - can be overridden per environment
    oracle_home: "E:\\Oracle\\Middleware\\Oracle_Home"
    backup_dir: "E:\\Oracle\\backup"
    java_source_dir: "E:\\Java_source"
    java_installer: "jdk-8u441-windows-x64.exe"
    java_install_dir: "E:\\jdk1.8.0_441"
    
    
    # WebLogic domain configuration
    weblogic_domain: "base_domain"
    
    # Source files on Ansible server
    ansible_source_dir: "/home/appadmin/Upgrade_weblogic_files"
    
    # Jenkins Pipeline Variables
    jenkins_build_number: "{{ jenkins_build_number | default('manual') }}"
    jenkins_job_name: "{{ jenkins_job_name | default('ansible-weblogic-upgrade') }}"
    
    # WebLogic Configuration Update Variables
    # These can be overridden via command line or Jenkins parameters
    weblogic_config_updates:
      - file: "{{ oracle_home }}\\oui\\.globalEnv.properties"
        regexp: "{{ java_home_regexp | default('^#.*Java.*Home.*') }}"
        line: "JAVA_HOME={{ java_install_dir }}\\bin\\java.exe"
        description: "Java Home Configuration"
        
      - file: "{{ oracle_home }}\\oui\\.globalEnv.properties"
        regexp: "{{ weblogic_home_regexp | default('^#.*WebLogic.*Home.*') }}"
        line: "WL_HOME={{ oracle_home }}\\wlserver"
        description: "WebLogic Home Configuration"
        
      - file: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\nodemanager\\nodemanager.properties"
        regexp: "{{ nodemanager_java_home_regexp | default('^JavaHome=.*') }}"
        line: "JavaHome={{ java_install_dir }}"
        description: "Node Manager Java Home"
        
      - file: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setNMJavaHome.cmd"
        regexp: "{{ setnmjavahome_regexp | default('^set.*JAVA_HOME.*') }}"
        line: "set JAVA_HOME={{ java_install_dir }}"
        description: "Set NM Java Home Script"
        
      - file: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setDomainEnv.cmd"
        regexp: "{{ setdomainenv_java_home_regexp | default('^set.*JAVA_HOME.*') }}"
        line: "set JAVA_HOME={{ java_install_dir }}"
        description: "Domain Environment Java Home"
        
      - file: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setDomainEnv.cmd"
        regexp: "{{ setdomainenv_path_regexp | default('^set.*PATH.*') }}"
        line: "set PATH=%JAVA_HOME%\\bin;%PATH%"
        description: "Domain Environment PATH"
    
    # Customizable regexp patterns (can be overridden)
    java_home_regexp: "{{ java_home_regexp | default('^#.*Java.*Home.*') }}"
    weblogic_home_regexp: "{{ weblogic_home_regexp | default('^#.*WebLogic.*Home.*') }}"
    nodemanager_java_home_regexp: "{{ nodemanager_java_home_regexp | default('^JavaHome=.*') }}"
    setnmjavahome_regexp: "{{ setnmjavahome_regexp | default('^set.*JAVA_HOME.*') }}"
    setdomainenv_java_home_regexp: "{{ setdomainenv_java_home_regexp | default('^set.*JAVA_HOME.*') }}"
    setdomainenv_path_regexp: "{{ setdomainenv_path_regexp | default('^set.*PATH.*') }}"
    
  pre_tasks:
    - name: Log Jenkins Pipeline Start
      debug:
        msg: |
          === Jenkins Pipeline Execution Started ===
          Build Number: {{ jenkins_build_number }}
          Job Name: {{ jenkins_job_name }}
          Target Host: {{ inventory_hostname }}
          Environment: PROD
          Timestamp: {{ ansible_date_time.iso8601 }}
          
  tasks:
    ### Ensure Backup Directory Exists
    - name: Create Backup Directory
      win_file:
        path: "{{ backup_dir }}"
        state: directory

    ### Define WebLogic Files for Backup
    - name: Set File Backup List
      set_fact:
        files_to_backup:
          - path: "{{ oracle_home }}\\oui\\.globalEnv.properties"
            description: "Oracle Global Environment Properties"
          - path: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\nodemanager\\nodemanager.properties"
            description: "Node Manager Properties"
          - path: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setNMJavaHome.cmd"
            description: "Node Manager Java Home Script"
          - path: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setDomainEnv.cmd"
            description: "Domain Environment Script"

    ### Backup WebLogic Configuration Files
    - name: Backup WebLogic Files with Timestamp
      win_shell: |
        $filePath = "{{ item.path }}"
        $backupDir = "{{ backup_dir }}"
        $timestamp = Get-Date -Format 'yyyyMMddHHmmss'
        $fileName = [System.IO.Path]::GetFileName($filePath)
        $backupFile = "$backupDir\$fileName`_$timestamp"
        
        If (Test-Path $filePath) {
            Copy-Item -Path $filePath -Destination $backupFile
            Write-Output "Backup created at $backupFile"
        } else {
            Write-Output "No existing file to backup: $filePath"
        }
      args:
        executable: powershell
      loop: "{{ files_to_backup }}"
      register: backup_results

    - name: Display Backup Status
      debug:
        msg: "{{ backup_results.results | map(attribute='stdout_lines') | list }}"

    ### Copy New WebLogic Configuration Files
    - name: Check if WebLogic files exist before replacement
      win_stat:
        path: "{{ item.dest }}"
      loop:
        - { src: ".globalEnv.properties", dest: "{{ oracle_home }}\\oui\\.globalEnv.properties" }
        - { src: "nodemanager.properties", dest: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\nodemanager\\nodemanager.properties" }
        - { src: "setNMJavaHome.cmd", dest: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setNMJavaHome.cmd" }
        - { src: "setDomainEnv.cmd", dest: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setDomainEnv.cmd" }
      register: file_check_results

    - name: Display file existence status
      debug:
        msg: "File {{ item.item.dest }} exists: {{ item.stat.exists }}"
      loop: "{{ file_check_results.results }}"

    - name: Display WebLogic Configuration Updates to be Applied
      debug:
        msg: |
          === WebLogic Configuration Updates ===
          File: {{ item.file }}
          Pattern: {{ item.regexp }}
          New Value: {{ item.line }}
          Description: {{ item.description }}
      loop: "{{ weblogic_config_updates }}"

    - name: Update WebLogic Configuration Files (Direct Modification)
      win_lineinfile:
        path: "{{ item.file }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      loop: "{{ weblogic_config_updates }}"
      when: 
        - item.file is defined
        - item.regexp is defined
        - item.line is defined
      register: file_update_results

    - name: Create WebLogic Configuration Files if they don't exist
      win_template:
        src: "{{ item.template_src }}"
        dest: "{{ item.dest }}"
      loop:
        - { dest: "{{ oracle_home }}\\oui\\.globalEnv.properties", template_src: "templates/weblogic/globalEnv.properties.j2" }
        - { dest: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\nodemanager\\nodemanager.properties", template_src: "templates/weblogic/nodemanager.properties.j2" }
        - { dest: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setNMJavaHome.cmd", template_src: "templates/weblogic/setNMJavaHome.cmd.j2" }
        - { dest: "{{ oracle_home }}\\user_projects\\domains\\{{ weblogic_domain }}\\bin\\setDomainEnv.cmd", template_src: "templates/weblogic/setDomainEnv.cmd.j2" }
      when: not item.stat.exists
      register: file_create_results

    - name: Verify file content after update
      win_shell: |
        $filePath = "{{ item.item.dest }}"
        if (Test-Path $filePath) {
          $content = Get-Content $filePath -Raw
          $lineCount = ($content -split "`n").Count
          $size = (Get-Item $filePath).Length
          Write-Output "File: $filePath - Lines: $lineCount - Size: $size bytes"
          
          # Check for key configuration values
          if ($content -match "JAVA_HOME") {
            Write-Output "✓ JAVA_HOME configuration found"
          }
          if ($content -match "{{ java_install_dir }}") {
            Write-Output "✓ Java path configuration updated"
          }
        } else {
          Write-Output "File: $filePath - NOT FOUND"
        }
      loop: "{{ file_check_results.results }}"
      register: file_verification_results

    - name: Display File Update Summary
      debug:
        msg: |
          === WebLogic Files Update Summary ===
          Files Checked: {{ file_check_results.results | length }}
          Files Updated: {{ file_update_results.results | default([]) | length }}
          Files Created: {{ file_create_results.results | default([]) | length }}
          Verification: {{ file_verification_results.results | map(attribute='stdout_lines') | list }}

    ### Uninstall Existing Java (Safe, Tolerant)
    - name: Uninstall existing Java versions
      win_shell: |
        $apps = Get-WmiObject -Class Win32_Product | Where-Object {
          $_.Name -like "Java*" -or $_.Name -like "*JDK*"
        }

        foreach ($app in $apps) {
          Write-Output "Uninstalling: $($app.Name)"
          try {
            $null = $app.Uninstall()
          } catch {
            Write-Output "Failed to uninstall $($app.Name): $($_.Exception.Message)"
          }
        }

        if (-not $apps) {
          Write-Output "No existing Java installations found."
        }
      args:
        executable: powershell
      register: uninstall_java_result
      ignore_errors: true

    - name: Display Java Uninstall Results
      debug:
        msg: "{{ uninstall_java_result.stdout_lines }}"

    ### Kill All Java Processes Before Installation
    - name: Kill all running Java processes
      win_shell: |
        $javaProcs = Get-Process java -ErrorAction SilentlyContinue
        if ($javaProcs) {
          Stop-Process -Name java -Force
          Write-Output "Java processes killed."
        } else {
          Write-Output "No Java processes running."
        }
      args:
        executable: powershell
      register: kill_java_result

    - name: Display Java Kill Result
      debug:
        msg: "{{ kill_java_result.stdout_lines }}"

    ### Copy Java Installer to Windows Server
    - name: Copy Java Installer to Windows Server
      win_copy:
        src: "{{ ansible_source_dir }}/{{ java_installer }}"
        dest: "{{ java_source_dir }}\\{{ java_installer }}"

    ### Install Java JDK
    - name: Install Java JDK
      win_shell: "{{ java_source_dir }}\\{{ java_installer }} /s INSTALLDIR={{ java_install_dir }}"
      args:
        chdir: "{{ java_source_dir }}"

    ### Set JAVA_HOME Environment Variable
    - name: Set JAVA_HOME Environment Variable
      win_environment:
        name: JAVA_HOME
        value: "{{ java_install_dir }}"
        level: machine

    ### Add Java to System PATH
    - name: Add Java to System PATH
      win_path:
        elements:
          - "{{ java_install_dir }}\\bin"

    ### Get WebLogic Version Using Installed Java
    - name: Get WebLogic Version
      win_shell: |
        $env:JAVA_HOME = "{{ java_install_dir }}"
        $env:PATH = "$env:JAVA_HOME\bin;$env:PATH"
        & "$env:JAVA_HOME\bin\java.exe" -cp "{{ oracle_home }}\wlserver\server\lib\weblogic.jar" weblogic.version
      register: weblogic_version_output

    - name: Display WebLogic Version
      debug:
        msg: "{{ weblogic_version_output.stdout_lines }}"

    ### Verify Java Installation
    - name: Verify Java Installation
      win_shell: |
        $env:JAVA_HOME = "{{ java_install_dir }}"
        $env:PATH = "$env:JAVA_HOME\bin;$env:PATH"
        & "$env:JAVA_HOME\bin\java.exe" -version
      register: java_version_output

    - name: Display Java Version
      debug:
        msg: "{{ java_version_output.stdout_lines }}"

  post_tasks:
    - name: Log Jenkins Pipeline Completion
      debug:
        msg: |
          === Jenkins Pipeline Execution Completed ===
          Build Number: {{ jenkins_build_number }}
          Job Name: {{ jenkins_job_name }}
          Target Host: {{ inventory_hostname }}
          Environment: PROD
          Completion Time: {{ ansible_date_time.iso8601 }}
          Status: SUCCESS
          
    - name: Generate Execution Summary Report
      set_fact:
        execution_summary:
          host: "{{ inventory_hostname }}"
          environment: "PROD"
          jenkins_build: "{{ jenkins_build_number }}"
          backup_files: "{{ backup_results.results | length }}"
          files_updated: "{{ file_update_results.results | default([]) | length }}"
          files_created: "{{ file_create_results.results | default([]) | length }}"
          java_uninstalled: "{{ uninstall_java_result.stdout_lines | length }}"
          java_installed: "{{ java_install_dir }}"
          weblogic_version: "{{ weblogic_version_output.stdout_lines | first | default('N/A') }}"
          java_version: "{{ java_version_output.stdout_lines | first | default('N/A') }}"
          execution_time: "{{ ansible_date_time.iso8601 }}"
          
    - name: Display Final Execution Summary
      debug:
        msg: |
          === FINAL EXECUTION SUMMARY ===
          Host: {{ execution_summary.host }}
          Environment: {{ execution_summary.environment }}
          Jenkins Build: {{ execution_summary.jenkins_build }}
          Backup Files: {{ execution_summary.backup_files }}
          Files Updated: {{ execution_summary.files_updated }}
          Files Created: {{ execution_summary.files_created }}
          Java Uninstalled: {{ execution_summary.java_uninstalled }}
          Java Installation Path: {{ execution_summary.java_installed }}
          WebLogic Version: {{ execution_summary.weblogic_version }}
          Java Version: {{ execution_summary.java_version }}
          Execution Time: {{ execution_summary.execution_time }}
          
    - name: Create Jenkins Pipeline Status File
      win_file:
        path: "C:\\temp\\jenkins_pipeline_status.json"
        state: file
        content: "{{ execution_summary | to_json }}"
      ignore_errors: yes
