---
- name: Apply WebLogic Patch using OPatch on Windows
  hosts: windows_dev_medgo
  gather_facts: no
  
  vars:
    # REQUIRED: WebLogic patch variables - MUST be provided by executor via command line
    # Example: ansible-playbook -i inventory Apply_Patch_weblogic.yml \
    #   -e "patch_number='35247514'" \
    #   -e "patch_file='p35247514_122130_Generic.zip'" \
    #   -e "oracle_home='E:\\Oracle\\Middleware\\Oracle_Home'" \
    #   -e "patch_local_path='/home/appadmin/patches/p35247514_122130_Generic.zip'" \
    #   -e "patch_remote_path='E:\\Oracle\\patches\\p35247514_122130_Generic.zip'" \
    #   -e "patch_extract_path='E:\\Oracle\\Middleware\\patches\\35247514'"
    
    # Patch identification
    patch_number: "{{ patch_number }}"
    patch_file: "{{ patch_file }}"
    
    # Oracle and WebLogic paths
    oracle_home: "{{ oracle_home }}"
    
    # Patch file paths
    patch_local_path: "{{ patch_local_path }}"
    patch_remote_path: "{{ patch_remote_path }}"
    patch_extract_path: "{{ patch_extract_path }}"
    
    # OPatch binary path
    opatch_bin_path: "{{ oracle_home }}\\OPatch"

  pre_tasks:
    - name: Validate Required Variables
      fail:
        msg: |
          Required variables must be provided via command line:
          
          Example:
          ansible-playbook -i inventory Apply_Patch_weblogic.yml \
            -e "patch_number='35247514'" \
            -e "patch_file='p35247514_122130_Generic.zip'" \
            -e "oracle_home='E:\\Oracle\\Middleware\\Oracle_Home'" \
            -e "patch_local_path='/home/appadmin/patches/p35247514_122130_Generic.zip'" \
            -e "patch_remote_path='E:\\Oracle\\patches\\p35247514_122130_Generic.zip'" \
            -e "patch_extract_path='E:\\Oracle\\Middleware\\patches\\35247514'"
          
          Variables provided:
          - patch_number: {{ patch_number | default('NOT PROVIDED') }}
          - patch_file: {{ patch_file | default('NOT PROVIDED') }}
          - oracle_home: {{ oracle_home | default('NOT PROVIDED') }}
          - patch_local_path: {{ patch_local_path | default('NOT PROVIDED') }}
          - patch_remote_path: {{ patch_remote_path | default('NOT PROVIDED') }}
          - patch_extract_path: {{ patch_extract_path | default('NOT PROVIDED') }}
      when: 
        - patch_number is not defined
        - patch_file is not defined
        - oracle_home is not defined
        - patch_local_path is not defined
        - patch_remote_path is not defined
        - patch_extract_path is not defined

    - name: Start WebLogic Patch Process
      debug:
        msg: |
          === WebLogic Patch Application Started ===
          Target Host: {{ inventory_hostname }}
          Environment: PROD
          Patch Number: {{ patch_number }}
          Patch File: {{ patch_file }}
          Oracle Home: {{ oracle_home }}
          Timestamp: {{ ansible_date_time.iso8601 }}

  tasks:
    - name: Create Patch Directory on Target
      win_file:
        path: "E:\\Oracle\\Middleware\\patches"
        state: directory

    - name: Copy Patch ZIP to Target Windows Server
      win_copy:
        src: "{{ patch_local_path }}"
        dest: "{{ patch_remote_path }}"

    - name: Extract Patch ZIP on Windows Server
      win_unzip:
        src: "{{ patch_remote_path }}"
        dest: "{{ patch_extract_path }}"
        creates: "{{ patch_extract_path }}\\{{ patch_number }}"

    - name: Display Contents of Patch Directory (for verification)
      win_shell: "Get-ChildItem -Path '{{ patch_extract_path }}' -Recurse"
      register: patch_dir_listing

    - name: Show Patch Files on Target
      debug:
        msg: "{{ patch_dir_listing.stdout_lines }}"

    - name: Apply WebLogic Patch using OPatch (echo y to confirm)
      win_shell: |
        set ORACLE_HOME={{ oracle_home }}
        set PATH={{ opatch_bin_path }};%PATH%
        cd {{ patch_extract_path }}
        echo y | opatch apply
      args:
        executable: cmd
      register: opatch_output

    - name: Show OPatch Output
      debug:
        msg: "{{ opatch_output.stdout_lines }}"

  post_tasks:
    - name: Log WebLogic Patch Completion
      debug:
        msg: |
          === WebLogic Patch Application Completed ===
          Target Host: {{ inventory_hostname }}
          Environment: PROD
          Patch Number: {{ patch_number }}
          Completion Time: {{ ansible_date_time.iso8601 }}
          Status: SUCCESS
          
    - name: Generate Execution Summary Report
      set_fact:
        execution_summary:
          host: "{{ inventory_hostname }}"
          environment: "PROD"
          patch_number: "{{ patch_number }}"
          patch_file: "{{ patch_file }}"
          oracle_home: "{{ oracle_home }}"
          patch_extracted: "{{ patch_dir_listing.stdout_lines | length }}"
          opatch_output: "{{ opatch_output.stdout_lines | length }}"
          execution_time: "{{ ansible_date_time.iso8601 }}"
          
    - name: Display Final Execution Summary
      debug:
        msg: |
          === FINAL EXECUTION SUMMARY ===
          Host: {{ execution_summary.host }}
          Environment: {{ execution_summary.environment }}
          Patch Number: {{ execution_summary.patch_number }}
          Patch File: {{ execution_summary.patch_file }}
          Oracle Home: {{ execution_summary.oracle_home }}
          Patch Files Extracted: {{ execution_summary.patch_extracted }}
          OPatch Output Lines: {{ execution_summary.opatch_output }}
          Execution Time: {{ execution_summary.execution_time }}

